cup:
  exact:
    - cup
  match:
    - cup.n.01
table:
  exact:
    - table
  match:
    - table.n.02
paper:
  exact:
    - paper
  match:
    - paper.n.01
block:
  exact:
    - block
  match:
    - block.n.01
jack:
  exact:
    - jack
  match:
jane:
  exact:
    - jane
  match:
sawyer:
  exact:
    - sawyer
  match:
movo:
  exact:
    - movo
  match:
orientation:
  exact:
    - angle
  match:
    - angle.n.01
speed:
  exact:
    - speed
  match:
    - speed.n.01
distance:
  exact:
    - near
  match:
    - near.r.01
above:
  exact:
    - over
    - above
  match:
    - above.r.02
    - over.r.01
order:
  exact:
  match:
radius:
  exact:
  match:
area:
  exact:
  match:
computer:
  exact:
    - computer
    - laptop
  match:
    - computer.n.01
    - laptop.n.01
book:
  exact:
    - book
  match:
    - book.n.01
plate:
  exact:
    - plate
  match:
    - plate.n.04
knife:
  exact:
    - knife
  match:
    - knife.n.01
gun:
  exact:
    - gun
  match:
    - gun.n.01
# bowl:
#   exact:
#     - bowl
#   match:
#     - bowl.n.01